# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Daley', :city => cities.first)

Country.create(:name => 'Afghanistan', :short => 'AF')
Country.create(:name => 'Aland Islands', :short => 'AX')
Country.create(:name => 'Albania', :short => 'AL')
Country.create(:name => 'Algeria', :short => 'DZ')
Country.create(:name => 'American Samoa', :short => 'AS')
Country.create(:name => 'Andorra', :short => 'AD')
Country.create(:name => 'Angola', :short => 'AO')
Country.create(:name => 'Anguilla', :short => 'AI')
Country.create(:name => 'Antarctica', :short => 'AQ')
Country.create(:name => 'Antigua And Barbuda', :short => 'AG')
Country.create(:name => 'Argentina', :short => 'AR')
Country.create(:name => 'Armenia', :short => 'AM')
Country.create(:name => 'Aruba', :short => 'AW')
Country.create(:name => 'Australia', :short => 'AU')
Country.create(:name => 'Austria', :short => 'AT')
Country.create(:name => 'Azerbaijan', :short => 'AZ')
Country.create(:name => 'Bahamas', :short => 'BS')
Country.create(:name => 'Bahrain', :short => 'BH')
Country.create(:name => 'Bangladesh', :short => 'BD')
Country.create(:name => 'Barbados', :short => 'BB')
Country.create(:name => 'Belarus', :short => 'BY')
Country.create(:name => 'Belgium', :short => 'BE')
Country.create(:name => 'Belize', :short => 'BZ')
Country.create(:name => 'Benin', :short => 'BJ')
Country.create(:name => 'Bermuda', :short => 'BM')
Country.create(:name => 'Bhutan', :short => 'BT')
Country.create(:name => 'Bolivia', :short => 'BO')
Country.create(:name => 'Bosnia And Herzegovina', :short => 'BA')
Country.create(:name => 'Botswana', :short => 'BW')
Country.create(:name => 'Bouvet Island', :short => 'BV')
Country.create(:name => 'Brazil', :short => 'BR')
Country.create(:name => 'British Indian Ocean Territory', :short => 'IO')
Country.create(:name => 'Brunei Darussalam', :short => 'BN')
Country.create(:name => 'Bulgaria', :short => 'BG')
Country.create(:name => 'Burkina Faso', :short => 'BF')
Country.create(:name => 'Burundi', :short => 'BI')
Country.create(:name => 'Cambodia', :short => 'KH')
Country.create(:name => 'Cameroon', :short => 'CM')
Country.create(:name => 'Canada', :short => 'CA')
Country.create(:name => 'Cape Verde', :short => 'CV')
Country.create(:name => 'Cayman Islands', :short => 'KY')
Country.create(:name => 'Central African Republic', :short => 'CF')
Country.create(:name => 'Chad', :short => 'TD')
Country.create(:name => 'Chile', :short => 'CL')
Country.create(:name => 'China', :short => 'CN')
Country.create(:name => 'Christmas Island', :short => 'CX')
Country.create(:name => 'Cocos (keeling) Islands', :short => 'CC')
Country.create(:name => 'Colombia', :short => 'CO')
Country.create(:name => 'Comoros', :short => 'KM')
Country.create(:name => 'Congo', :short => 'CG')
Country.create(:name => 'Congo, The Democratic Republic Of The', :short => 'CD')
Country.create(:name => 'Cook Islands', :short => 'CK')
Country.create(:name => 'Costa Rica', :short => 'CR')
Country.create(:name => 'Cote Divoire', :short => 'CI')
Country.create(:name => 'Croatia', :short => 'HR')
Country.create(:name => 'Cuba', :short => 'CU')
Country.create(:name => 'Cyprus', :short => 'CY')
Country.create(:name => 'Czech Republic', :short => 'CZ')
Country.create(:name => 'Denmark', :short => 'DK')
Country.create(:name => 'Djibouti', :short => 'DJ')
Country.create(:name => 'Dominica', :short => 'DM')
Country.create(:name => 'Dominican Republic', :short => 'DO')
Country.create(:name => 'Ecuador', :short => 'EC')
Country.create(:name => 'Egypt', :short => 'EG')
Country.create(:name => 'El Salvador', :short => 'SV')
Country.create(:name => 'Equatorial Guinea', :short => 'GQ')
Country.create(:name => 'Eritrea', :short => 'ER')
Country.create(:name => 'Estonia', :short => 'EE')
Country.create(:name => 'Ethiopia', :short => 'ET')
Country.create(:name => 'Falkland Islands (malvinas)', :short => 'FK')
Country.create(:name => 'Faroe Islands', :short => 'FO')
Country.create(:name => 'Fiji', :short => 'FJ')
Country.create(:name => 'Finland', :short => 'FI')
Country.create(:name => 'France', :short => 'FR')
Country.create(:name => 'French Guiana', :short => 'GF')
Country.create(:name => 'French Polynesia', :short => 'PF')
Country.create(:name => 'French Southern Territories', :short => 'TF')
Country.create(:name => 'Gabon', :short => 'GA')
Country.create(:name => 'Gambia', :short => 'GM')
Country.create(:name => 'Georgia', :short => 'GE')
Country.create(:name => 'Germany', :short => 'DE')
Country.create(:name => 'Ghana', :short => 'GH')
Country.create(:name => 'Gibraltar', :short => 'GI')
Country.create(:name => 'Greece', :short => 'GR')
Country.create(:name => 'Greenland', :short => 'GL')
Country.create(:name => 'Grenada', :short => 'GD')
Country.create(:name => 'Guadeloupe', :short => 'GP')
Country.create(:name => 'Guam', :short => 'GU')
Country.create(:name => 'Guatemala', :short => 'GT')
Country.create(:name => 'Guernsey', :short => 'GG')
Country.create(:name => 'Guinea', :short => 'GN')
Country.create(:name => 'Guinea-bissau', :short => 'GW')
Country.create(:name => 'Guyana', :short => 'GY')
Country.create(:name => 'Haiti', :short => 'HT')
Country.create(:name => 'Heard Island And Mcdonald Islands', :short => 'HM')
Country.create(:name => 'Honduras', :short => 'HN')
Country.create(:name => 'Hong Kong', :short => 'HK')
Country.create(:name => 'Hungary', :short => 'HU')
Country.create(:name => 'Iceland', :short => 'IS')
Country.create(:name => 'India', :short => 'IN')
Country.create(:name => 'Indonesia', :short => 'ID')
Country.create(:name => 'Iran, Islamic Republic Of', :short => 'IR')
Country.create(:name => 'Iraq', :short => 'IQ')
Country.create(:name => 'Ireland', :short => 'IE')
Country.create(:name => 'Isle Of Man', :short => 'IM')
Country.create(:name => 'Israel', :short => 'IL')
Country.create(:name => 'Italy', :short => 'IT')
Country.create(:name => 'Jamaica', :short => 'JM')
Country.create(:name => 'Japan', :short => 'JP')
Country.create(:name => 'Jersey', :short => 'JE')
Country.create(:name => 'Jordan', :short => 'JO')
Country.create(:name => 'Kazakhstan', :short => 'KZ')
Country.create(:name => 'Kenya', :short => 'KE')
Country.create(:name => 'Kiribati', :short => 'KI')
Country.create(:name => 'Korea, Democratic Peoples Republic Of', :short => 'KP')
Country.create(:name => 'Korea, Republic Of', :short => 'KR')
Country.create(:name => 'Kuwait', :short => 'KW')
Country.create(:name => 'Kyrgyzstan', :short => 'KG')
Country.create(:name => 'Lao Peoples Democratic Republic', :short => 'LA')
Country.create(:name => 'Latvia', :short => 'LV')
Country.create(:name => 'Lebanon', :short => 'LB')
Country.create(:name => 'Lesotho', :short => 'LS')
Country.create(:name => 'Liberia', :short => 'LR')
Country.create(:name => 'Libyan Arab Jamahiriya', :short => 'LY')
Country.create(:name => 'Liechtenstein', :short => 'LI')
Country.create(:name => 'Lithuania', :short => 'LT')
Country.create(:name => 'Luxembourg', :short => 'LU')
Country.create(:name => 'Macao', :short => 'MO')
Country.create(:name => 'Macedonia, The Former Yugoslav Republic Of', :short => 'MK')
Country.create(:name => 'Madagascar', :short => 'MG')
Country.create(:name => 'Malawi', :short => 'MW')
Country.create(:name => 'Malaysia', :short => 'MY')
Country.create(:name => 'Maldives', :short => 'MV')
Country.create(:name => 'Mali', :short => 'ML')
Country.create(:name => 'Malta', :short => 'MT')
Country.create(:name => 'Marshall Islands', :short => 'MH')
Country.create(:name => 'Martinique', :short => 'MQ')
Country.create(:name => 'Mauritania', :short => 'MR')
Country.create(:name => 'Mauritius', :short => 'MU')
Country.create(:name => 'Mayotte', :short => 'YT')
Country.create(:name => 'Mexico', :short => 'MX')
Country.create(:name => 'Micronesia, Federated States Of', :short => 'FM')
Country.create(:name => 'Moldova', :short => 'MD')
Country.create(:name => 'Monaco', :short => 'MC')
Country.create(:name => 'Mongolia', :short => 'MN')
Country.create(:name => 'Montenegro', :short => 'ME')
Country.create(:name => 'Montserrat', :short => 'MS')
Country.create(:name => 'Morocco', :short => 'MA')
Country.create(:name => 'Mozambique', :short => 'MZ')
Country.create(:name => 'Myanmar', :short => 'MM')
Country.create(:name => 'Namibia', :short => 'NA')
Country.create(:name => 'Nauru', :short => 'NR')
Country.create(:name => 'Nepal', :short => 'NP')
Country.create(:name => 'Netherlands', :short => 'NL')
Country.create(:name => 'Netherlands Antilles', :short => 'AN')
Country.create(:name => 'New Caledonia', :short => 'NC')
Country.create(:name => 'New Zealand', :short => 'NZ')
Country.create(:name => 'Nicaragua', :short => 'NI')
Country.create(:name => 'Niger', :short => 'NE')
Country.create(:name => 'Nigeria', :short => 'NG')
Country.create(:name => 'Niue', :short => 'NU')
Country.create(:name => 'Norfolk Island', :short => 'NF')
Country.create(:name => 'Northern Mariana Islands', :short => 'MP')
Country.create(:name => 'Norway', :short => 'NO')
Country.create(:name => 'Oman', :short => 'OM')
Country.create(:name => 'Pakistan', :short => 'PK')
Country.create(:name => 'Palau', :short => 'PW')
Country.create(:name => 'Palestinian Territory, Occupied', :short => 'PS')
Country.create(:name => 'Panama', :short => 'PA')
Country.create(:name => 'Papua New Guinea', :short => 'PG')
Country.create(:name => 'Paraguay', :short => 'PY')
Country.create(:name => 'Peru', :short => 'PE')
Country.create(:name => 'Philippines', :short => 'PH')
Country.create(:name => 'Pitcairn', :short => 'PN')
Country.create(:name => 'Poland', :short => 'PL')
Country.create(:name => 'Portugal', :short => 'PT')
Country.create(:name => 'Puerto Rico', :short => 'PR')
Country.create(:name => 'Qatar', :short => 'QA')
Country.create(:name => 'Reunion', :short => 'RE')
Country.create(:name => 'Romania', :short => 'RO')
Country.create(:name => 'Russian Federation', :short => 'RU')
Country.create(:name => 'Rwanda', :short => 'RW')
Country.create(:name => 'Saint Barthelemy', :short => 'BL')
Country.create(:name => 'Saint Helena', :short => 'SH')
Country.create(:name => 'Saint Kitts And Nevis', :short => 'KN')
Country.create(:name => 'Saint Lucia', :short => 'LC')
Country.create(:name => 'Saint Martin', :short => 'MF')
Country.create(:name => 'Saint Pierre And Miquelon', :short => 'PM')
Country.create(:name => 'Saint Vincent And The Grenadines', :short => 'VC')
Country.create(:name => 'Samoa', :short => 'WS')
Country.create(:name => 'San Marino', :short => 'SM')
Country.create(:name => 'Sao Tome And Principe', :short => 'ST')
Country.create(:name => 'Saudi Arabia', :short => 'SA')
Country.create(:name => 'Senegal', :short => 'SN')
Country.create(:name => 'Serbia', :short => 'RS')
Country.create(:name => 'Seychelles', :short => 'SC')
Country.create(:name => 'Sierra Leone', :short => 'SL')
Country.create(:name => 'Singapore', :short => 'SG')
Country.create(:name => 'Slovakia', :short => 'SK')
Country.create(:name => 'Slovenia', :short => 'SI')
Country.create(:name => 'Solomon Islands', :short => 'SB')
Country.create(:name => 'Somalia', :short => 'SO')
Country.create(:name => 'South Africa', :short => 'ZA')
Country.create(:name => 'South Georgia And The South Sandwich Islands', :short => 'GS')
Country.create(:name => 'Spain', :short => 'ES')
Country.create(:name => 'Sri Lanka', :short => 'LK')
Country.create(:name => 'Sudan', :short => 'SD')
Country.create(:name => 'Suriname', :short => 'SR')
Country.create(:name => 'Svalbard And Jan Mayen', :short => 'SJ')
Country.create(:name => 'Swaziland', :short => 'SZ')
Country.create(:name => 'Sweden', :short => 'SE')
Country.create(:name => 'Switzerland', :short => 'CH')
Country.create(:name => 'Syrian Arab Republic', :short => 'SY')
Country.create(:name => 'Taiwan, Province Of China', :short => 'TW')
Country.create(:name => 'Tajikistan', :short => 'TJ')
Country.create(:name => 'Tanzania, United Republic Of', :short => 'TZ')
Country.create(:name => 'Thailand', :short => 'TH')
Country.create(:name => 'Timor-leste', :short => 'TL')
Country.create(:name => 'Togo', :short => 'TG')
Country.create(:name => 'Tokelau', :short => 'TK')
Country.create(:name => 'Tonga', :short => 'TO')
Country.create(:name => 'Trinidad And Tobago', :short => 'TT')
Country.create(:name => 'Tunisia', :short => 'TN')
Country.create(:name => 'Turkey', :short => 'TR')
Country.create(:name => 'Turkmenistan', :short => 'TM')
Country.create(:name => 'Turks And Caicos Islands', :short => 'TC')
Country.create(:name => 'Tuvalu', :short => 'TV')
Country.create(:name => 'Uganda', :short => 'UG')
Country.create(:name => 'Ukraine', :short => 'UA')
Country.create(:name => 'United Arab Emirates', :short => 'AE')
Country.create(:name => 'United Kingdom', :short => 'GB')
united_states = Country.create(:name => 'United States', :short => 'US')
Country.create(:name => 'United States Minor Outlying Islands', :short => 'UM')
Country.create(:name => 'Uruguay', :short => 'UY')
Country.create(:name => 'Uzbekistan', :short => 'UZ')
Country.create(:name => 'Vanuatu', :short => 'VU')
Country.create(:name => 'Vatican City State', :short => 'VA')
Country.create(:name => 'Venezuela', :short => 'VE')
Country.create(:name => 'Viet Nam', :short => 'VN')
Country.create(:name => 'Virgin Islands, British', :short => 'VG')
Country.create(:name => 'Virgin Islands, U.s.', :short => 'VI')
Country.create(:name => 'Wallis And Futuna', :short => 'WF')
Country.create(:name => 'Western Sahara', :short => 'EH')
Country.create(:name => 'Yemen', :short => 'YE')
Country.create(:name => 'Zambia', :short => 'ZM')
Country.create(:name => 'Zimbabwe', :short => 'ZW')

Language.create(:name =>'Abkhazian', :code => 'ab')
Language.create(:name =>'Afar', :code => 'aa')
Language.create(:name =>'Afrikaans', :code => 'af')
Language.create(:name =>'Albanian', :code => 'sq')
Language.create(:name =>'Amharic', :code => 'am')
Language.create(:name =>'Arabic', :code => 'ar')
Language.create(:name =>'Armenian', :code => 'hy')
Language.create(:name =>'Assamese', :code => 'as')
Language.create(:name =>'Aymara', :code => 'ay')
Language.create(:name =>'Azerbaijani', :code => 'az')
Language.create(:name =>'Bashkir', :code => 'ba')
Language.create(:name =>'Basque', :code => 'eu')
Language.create(:name =>'Bengali (Bangla)', :code => 'bn')
Language.create(:name =>'Bhutani', :code => 'dz')
Language.create(:name =>'Bihari', :code => 'bh')
Language.create(:name =>'Bislama', :code => 'bi')
Language.create(:name =>'Breton', :code => 'br')
Language.create(:name =>'Bulgarian', :code => 'bg')
Language.create(:name =>'Burmese', :code => 'my')
Language.create(:name =>'Byelorussian (Belarusian)', :code => 'be')
Language.create(:name =>'Cambodian', :code => 'km')
Language.create(:name =>'Catalan', :code => 'ca')
Language.create(:name =>'Cherokee', :code => ' ')
Language.create(:name =>'Chewa', :code => ' ')
Language.create(:name =>'Chinese (Simplified)', :code => 'zh')
Language.create(:name =>'Chinese (Traditional)', :code => 'zh')
Language.create(:name =>'Corsican', :code => 'co')
Language.create(:name =>'Croatian', :code => 'hr')
Language.create(:name =>'Czech', :code => 'cs')
Language.create(:name =>'Danish', :code => 'da')
Language.create(:name =>'Divehi', :code => ' ')
Language.create(:name =>'Dutch', :code => 'nl')
Language.create(:name =>'Edo', :code => ' ')
Language.create(:name =>'English', :code => 'en')
Language.create(:name =>'Esperanto', :code => 'eo')
Language.create(:name =>'Estonian', :code => 'et')
Language.create(:name =>'Faeroese', :code => 'fo')
Language.create(:name =>'Farsi', :code => 'fa')
Language.create(:name =>'Fiji', :code => 'fj')
Language.create(:name =>'Finnish', :code => 'fi')
Language.create(:name =>'Flemish', :code => ' ')
Language.create(:name =>'French', :code => 'fr')
Language.create(:name =>'Frisian', :code => 'fy')
Language.create(:name =>'Fulfulde', :code => ' ')
Language.create(:name =>'Galician', :code => 'gl')
Language.create(:name =>'Gaelic (Scottish)', :code => 'gd')
Language.create(:name =>'Gaelic (Manx)', :code => 'gv')
Language.create(:name =>'Georgian', :code => 'ka')
Language.create(:name =>'German', :code => 'de')
Language.create(:name =>'Greek', :code => 'el')
Language.create(:name =>'Greenlandic', :code => 'kl')
Language.create(:name =>'Guarani', :code => 'gn')
Language.create(:name =>'Gujarati', :code => 'gu')
Language.create(:name =>'Hausa', :code => 'ha')
Language.create(:name =>'Hawaiian', :code => ' ')
Language.create(:name =>'Hebrew', :code => 'he, iw')
Language.create(:name =>'Hindi', :code => 'hi')
Language.create(:name =>'Hungarian', :code => 'hu')
Language.create(:name =>'Ibibio', :code => ' ')
Language.create(:name =>'Icelandic', :code => 'is')
Language.create(:name =>'Igbo', :code => ' ')
Language.create(:name =>'Indonesian', :code => 'id, in')
Language.create(:name =>'Interlingua', :code => 'ia')
Language.create(:name =>'Interlingue', :code => 'ie')
Language.create(:name =>'Inuktitut', :code => 'iu')
Language.create(:name =>'Inupiak', :code => 'ik')
Language.create(:name =>'Irish', :code => 'ga')
Language.create(:name =>'Italian', :code => 'it')
Language.create(:name =>'Japanese', :code => 'ja')
Language.create(:name =>'Javanese', :code => 'jv')
Language.create(:name =>'Kannada', :code => 'kn')
Language.create(:name =>'Kanuri', :code => ' ')
Language.create(:name =>'Kashmiri', :code => 'ks')
Language.create(:name =>'Kazakh', :code => 'kk')
Language.create(:name =>'Kinyarwanda (Ruanda)', :code => 'rw')
Language.create(:name =>'Kirghiz', :code => 'ky')
Language.create(:name =>'Kirundi (Rundi)', :code => 'rn')
Language.create(:name =>'Konkani', :code => ' ')
Language.create(:name =>'Korean', :code => 'ko')
Language.create(:name =>'Kurdish', :code => 'ku')
Language.create(:name =>'Laothian', :code => 'lo')
Language.create(:name =>'Latin', :code => 'la')
Language.create(:name =>'Latvian (Lettish)', :code => 'lv')
Language.create(:name =>'Limburgish ( Limburger)', :code => 'li')
Language.create(:name =>'Lingala', :code => 'ln')
Language.create(:name =>'Lithuanian', :code => 'lt')
Language.create(:name =>'Macedonian', :code => 'mk')
Language.create(:name =>'Malagasy', :code => 'mg')
Language.create(:name =>'Malay', :code => 'ms')
Language.create(:name =>'Malayalam', :code => 'ml')
Language.create(:name =>' ', :code => ' ')
Language.create(:name =>'Maltese', :code => 'mt')
Language.create(:name =>'Maori', :code => 'mi')
Language.create(:name =>'Marathi', :code => 'mr')
Language.create(:name =>'Moldavian', :code => 'mo')
Language.create(:name =>'Mongolian', :code => 'mn')
Language.create(:name =>'Nauru', :code => 'na')
Language.create(:name =>'Nepali', :code => 'ne')
Language.create(:name =>'Norwegian', :code => 'no')
Language.create(:name =>'Occitan', :code => 'oc')
Language.create(:name =>'Oriya', :code => 'or')
Language.create(:name =>'Oromo (Afan, Galla)', :code => 'om')
Language.create(:name =>'Papiamentu', :code => ' ')
Language.create(:name =>'Pashto (Pushto)', :code => 'ps')
Language.create(:name =>'Polish', :code => 'pl')
Language.create(:name =>'Portuguese', :code => 'pt')
Language.create(:name =>'Punjabi', :code => 'pa')
Language.create(:name =>'Quechua', :code => 'qu')
Language.create(:name =>'Rhaeto-Romance', :code => 'rm')
Language.create(:name =>'Romanian', :code => 'ro')
Language.create(:name =>'Russian', :code => 'ru')
Language.create(:name =>'Sami (Lappish)', :code => ' ')
Language.create(:name =>'Samoan', :code => 'sm')
Language.create(:name =>'Sangro', :code => 'sg')
Language.create(:name =>'Sanskrit', :code => 'sa')
Language.create(:name =>'Serbian', :code => 'sr')
Language.create(:name =>'Serbo-Croatian', :code => 'sh')
Language.create(:name =>'Sesotho', :code => 'st')
Language.create(:name =>'Setswana', :code => 'tn')
Language.create(:name =>'Shona', :code => 'sn')
Language.create(:name =>'Sindhi', :code => 'sd')
Language.create(:name =>'Sinhalese', :code => 'si')
Language.create(:name =>'Siswati', :code => 'ss')
Language.create(:name =>'Slovak', :code => 'sk')
Language.create(:name =>'Slovenian', :code => 'sl')
Language.create(:name =>'Somali', :code => 'so')
Language.create(:name =>'Spanish', :code => 'es')
Language.create(:name =>'Sundanese', :code => 'su')
Language.create(:name =>'Swahili (Kiswahili)', :code => 'sw')
Language.create(:name =>'Swedish', :code => 'sv')
Language.create(:name =>'Syriac', :code => ' ')
Language.create(:name =>'Tagalog', :code => 'tl')
Language.create(:name =>'Tajik', :code => 'tg')
Language.create(:name =>'Tamazight', :code => ' ')
Language.create(:name =>'Tamil', :code => 'ta')
Language.create(:name =>'Tatar', :code => 'tt')
Language.create(:name =>'Telugu', :code => 'te')
Language.create(:name =>'Thai', :code => 'th')
Language.create(:name =>'Tibetan', :code => 'bo')
Language.create(:name =>'Tigrinya', :code => 'ti')
Language.create(:name =>'Tonga', :code => 'to')
Language.create(:name =>'Tsonga', :code => 'ts')
Language.create(:name =>'Turkish', :code => 'tr')
Language.create(:name =>'Turkmen', :code => 'tk')
Language.create(:name =>'Twi', :code => 'tw')
Language.create(:name =>'Uighur', :code => 'ug')
Language.create(:name =>'Ukrainian', :code => 'uk')
Language.create(:name =>'Urdu', :code => 'ur')
Language.create(:name =>'Uzbek', :code => 'uz')
Language.create(:name =>'Venda', :code => ' ')
Language.create(:name =>'Vietnamese', :code => 'vi')
Language.create(:name =>'Volapuk', :code => 'vo')
Language.create(:name =>'Welsh', :code => 'cy')
Language.create(:name =>'Wolof', :code => 'wo')
Language.create(:name =>'Xhosa', :code => 'xh')
Language.create(:name =>'Yi', :code => ' ')
Language.create(:name =>'Yiddish', :code => 'yi, ji')
Language.create(:name =>'Yoruba', :code => 'yo')
Language.create(:name =>'Zulu', :code => 'zu')




u = User.new
u.first_name = "Michael"
u.last_name = "Darmousseh"
u.login = "admin"
u.email = "michael.darmousseh@gmail.com"
u.password = "michael"
u.password_confirmation = "michael"
u.terms = "1"
u.roles = ["moderator", "admin", "superadmin"]
u.save
u.activate!

